version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: mydb
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  sso:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    environment:
      DSN: postgres://postgres:postgre@db:5432/mydb?sslmode=disable
    command: go run cmd/sso/main.go --config=./config/local.yaml
    ports:
      - "50051:50051"

volumes:
  db_data: