version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  migrate:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:secret@db:5432/mydb?sslmode=disable
    command: go run cmd/sso/main.go -storage "$DB_URL" -migration "migrations"

volumes:
  db_data: