env: "local" # dev, prod
dsn: postgres://postgres:postgre@db:5432/mydb?sslmode=disable # место хранения базы данных
token_ttl: 1h # время жизни токена в секунда
grpc:
  port: 50051 # порт gRPC сервера
  timeout: 5s # таймаут gRPC запросов в секундах